# The move_base package creates and calculates  a path or a trajectory to the goal position, and navigates the robot
# along that path. The set of parameters in this configuration file customize this particular behavior.

TrajectoryPlannerROS:

# Forward Simulation Parameter
# sim_time is the amount of time to forward-simulate trajectories in seconds.
# controller_frequency is  the frequency at which the controller is called in Hz.
  sim_time: 1.0
  controller_frequency: 10
# Trajectory Scoring
# The pdist_sclale is the weighting for how much the controller should stay close to the path it was given.
# It is the distance to path from the endpoint of the trajectory in map cells or meters depending on the meter_scoring parameter
# The pdsit_scale is set to it default value 6.0.
  meter_scoring: false
  pdist_scale: 0.6

# Goal Tolerance Parameters
# yaw and xy goal tolerances
# These tolerance help define how close the robot's pose can be to the goal position.
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05

# Robot Configuration Parameters
# acc_lim_x is the x acceleration limit of the robot in meters/sec^2
# acc_lim_y is the y acceleration limit of the robot in meters/sec^2
# acc_lim_theta is the rotational acceleration limit of the robot in radians/sec^2
# max_vel_x is the maximum rotational velocty allowed for the base in radians/sec
# min_vel_x is the  minimum rational velocity allowed for the base in radians/sec
# min_vel_theta  is the minimum rotational velocity allowed for the base in radians/sec
# max_vel_theta  is the maximum rotational velocity allowed for the base in radians/sec
# min_in_place_vel_theta is the minimum rotational velocity allowed for the base while performing in-place rotations in radians/sec
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

# holonomic_robot is use to determine whether velocity commands are generated for a holonomic or non-holonomic robot. For holonomic robots,
# strafing velocity commands may be issued to the base. For non-holonomic robots, no strafing velocity commands will be issued.
  holonomic_robot: false

