# For the list of parameters common to both types of costmaps the laser sensor is the source for observations.


map_type: costmap
obstacle_range: 5.0
raytrace_range: 8.0
transform_tolerance: 0.2
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
